### ISSUE TITLE
Add a link to your StackOverflow profile

### ISSUE THREAD

**Issue by IonicaBizau** [nuvipannu/resume#3]
...because you can! :joy:

**Comment by nuvipannu** [comment]
Oh good point! :+1:  Good looking out, as always :sparkling_heart:

**Comment by IonicaBizau** [comment]
:smile:

**Comment by nuvipannu** [comment]
I did it! Thanks again!! :grin:

**Comment by IonicaBizau** [comment]
:+1: :grinning:
